config/routes.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011   Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012   Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  #
  # dmsf controller
  #   /projects/<project>/dmsf
  #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
  ##
  post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
  get '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate', :as => 'notify_activate_dmsf'
  get '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf'
  get '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete', :as => 'delete_dmsf'
  post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
  post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
  post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation'
  post '/projects/:id/dmsf/tag_changed', :controller => 'dmsf', :action => 'tag_changed', :as => 'tag_changed'
  post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'
  post '/projects/:id/dmsf/entries/email', :controller => 'dmsf', :action => 'entries_email'
  get '/projects/:id/dmsf/entries/download_email_entries', :controller => 'dmsf', :action => 'download_email_entries', :as => 'download_email_entries'
  get '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock', :as => 'lock_dmsf'
  get '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock', :as => 'unlock_dmsf'
  get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show', :as => 'dmsf_folder'
  get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new', :as => 'new_dmsf'
  get '/projects/:id/dmsf/edit', :controller=> 'dmsf', :action => 'edit', :as => 'edit_dmsf'
  get '/projects/:id/dmsf/edit/root', :controller=> 'dmsf', :action => 'edit_root', :as => 'edit_root_dmsf'

  #
  # dmsf_state controller
  #   /projects/<project>/dmsf/state
  ##
  post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save'


  #
  #  dmsf_upload controller
  #   /projects/<project>/dmsf/upload - dmsf_upload controller
  ##

  post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
  post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
  post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
  
  #
  # dmsf_files controller
  #   /dmsf/files/<file id>
  ##
  get '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate', :as => 'notify_activate_dmsf_files'
  get '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf_files'
  get '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock', :as => 'lock_dmsf_files'
  get '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock', :as => 'unlock_dmsf_files'
  post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete', :as => 'delete_dmsf_files'
  post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
  get '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision', :as => 'delete_revision'
  get '/dmsf/files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => '' # Otherwise will not route nil download param
  get '/dmsf/files/:id/download/:download', :controller => 'dmsf_files', :action => 'show'
  get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show', :as => 'dmsf_file'
  delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'

  #
  # files_copy controller
  #   /dmsf/files/<file id>/copy
  ##
  post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
  post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
  get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new', :as => 'copy_file'

  #
  # folders_copy controller
  #   /dmsf/folders/<folder id>/copy
  ##
  #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
  post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
  get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new', :as => 'copy_folder'

  #
  # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
  #   /dmsf/webdav
  mount DAV4Rack::Handler.new(
    :root_uri_path => "/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller
  ), :at => "/dmsf/webdav"
  
  # Approval workflow    
  resources :dmsf_workflows do
    member do
      get 'autocomplete_for_user'
      get 'action'
      get 'assign'
      get 'log'
      post 'new_action'
      get 'start'
      post 'assignment'
    end
  end
  
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put    
  
  # Links
  resources :dmsf_links do
    member do      
    end    
  end  
  
end

app/models/dmsf_workflow.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Picman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class DmsfWorkflow < ActiveRecord::Base 
  has_many :dmsf_workflow_steps, :dependent => :destroy, :order => 'step ASC, operator DESC'

  validates_uniqueness_of :name, :case_sensitive => false
  validates :name, :presence => true
  validates_length_of :name, :maximum => 255
  
  STATE_NONE = nil
  STATE_ASSIGNED = 3
  STATE_WAITING_FOR_APPROVAL = 1
  STATE_APPROVED = 2
  STATE_REJECTED = 4
  
  def participiants
    users = Array.new
    self.dmsf_workflow_steps.each do |step|
      users << step.user unless users.include? step.user
    end
    users
  end

  def self.workflows(project)
    project ? where(:project_id => project) : where('project_id IS NULL')      
  end

  def project          
    Project.find_by_id(project_id) if project_id
  end

  def to_s
    name
  end   

  def reorder_steps(step, move_to)
    DmsfWorkflow.transaction do
      case move_to
        when 'highest'          
          unless step == 1            
            dmsf_workflow_steps.each do |ws|              
              if ws.step < step
               return false unless ws.update_attribute('step', ws.step + 1)               
              elsif ws.step == step                
                return false unless ws.update_attribute('step', 1)
              end            
            end          
          end
        when 'higher'
          unless step == 1            
            dmsf_workflow_steps.each do |ws|
              if ws.step == step - 1                                
                return false unless ws.update_attribute('step', step)
              elsif ws.step == step                
                return false unless ws.update_attribute('step', step - 1)
              end            
            end          
          end
        when 'lower'
          unless step == dmsf_workflow_steps.collect{|s| s.step}.uniq.count            
            dmsf_workflow_steps.each do |ws|
              if ws.step == step + 1                
                return false unless ws.update_attribute('step', step)                
              elsif ws.step == step                
                return false unless ws.update_attribute('step', step + 1)                
              end              
            end            
          end
        when 'lowest'                   
          size = dmsf_workflow_steps.collect{|s| s.step}.uniq.count
          unless step == size
            dmsf_workflow_steps.each do |ws|                            
              if ws.step > step                
                return false unless ws.update_attribute('step', ws.step - 1)
              elsif ws.step == step                
                return false unless ws.update_attribute('step', size)
              end
            end            
          end                            
      end     
    end
    return reload    
  end
  
  def delegates(q, dmsf_workflow_step_assignment_id, dmsf_file_revision_id)        
    if dmsf_workflow_step_assignment_id && dmsf_file_revision_id
      sql = [
        'id NOT IN (SELECT a.user_id FROM dmsf_workflow_step_assignments a WHERE id = ?) AND id IN (SELECT m.user_id FROM members m JOIN dmsf_files f ON f.project_id = m.project_id JOIN dmsf_file_revisions r ON r.dmsf_file_id = f.id WHERE r.id = ?)', 
        dmsf_workflow_step_assignment_id, 
        dmsf_file_revision_id]
    elsif project
      sql = ['id IN (SELECT user_id FROM members WHERE project_id = ?)', project.id]
    else
      sql = '1=1'
    end
    
    if q.present?
      User.active.sorted.where(sql).like(q)
    else
      User.active.sorted.where(sql)
    end    
  end
  
  def next_assignments(dmsf_file_revision_id)    
    results = Array.new  
    nsteps = self.dmsf_workflow_steps.collect{|s| s.step}.uniq
    nsteps.each do |i|
      step_is_finished = false      
      steps = self.dmsf_workflow_steps.collect{|s| s.step == i ? s : nil}.compact
      steps.each do |step|
        step.dmsf_workflow_step_assignments.each do |assignment|
          if assignment.dmsf_file_revision_id == dmsf_file_revision_id
            assignment.dmsf_workflow_step_actions.each do |action|
              case action.action
              when DmsfWorkflowStepAction::ACTION_APPROVE
                step_is_finished = true
                # Try to find another unfinished AND step  
                exists = false
                stps = self.dmsf_workflow_steps.collect{|s| (s.step == i && s.operator == DmsfWorkflowStep::OPERATOR_AND) ? s : nil}.compact
                stps.each do |s|
                  s.dmsf_workflow_step_assignments.each do |a|
                    exists = a.add?(dmsf_file_revision_id)                    
                    break if exists                    
                  end
                end  
                step_is_finished = false if exists
                break
              when DmsfWorkflowStepAction::ACTION_REJECT
                return Array.new              
              end
            end
          end
          break if step_is_finished
        end 
        if step_is_finished
          break        
        else
          steps.each do |step|
            step.dmsf_workflow_step_assignments.each do |assignment|              
              results << assignment if assignment.add?(dmsf_file_revision_id)              
            end
          end
          return results
        end
      end
    end
    results
  end
  
  def self.assignments_to_users_str(assignments)
    str = ''
    if assignments      
      assignments.each_with_index do |assignment, index|        
        if index > 0
          str << ', '
        end
        str << assignment.user.name        
      end
    end
    str    
  end
   
  def assign(dmsf_file_revision_id)
    dmsf_workflow_steps.each do |ws|
      ws.assign(dmsf_file_revision_id)
    end
  end
  
  def try_finish(revision, action, user_id)         
    case action.action
      when DmsfWorkflowStepAction::ACTION_APPROVE   
        assignments = self.next_assignments revision.id
        return false unless assignments.empty?
        revision.update_attribute(:workflow, DmsfWorkflow::STATE_APPROVED)
        return true
      when DmsfWorkflowStepAction::ACTION_REJECT
        revision.update_attribute(:workflow, DmsfWorkflow::STATE_REJECTED)
        return true
      when DmsfWorkflowStepAction::ACTION_DELEGATE        
        self.dmsf_workflow_steps.each do |step|
          step.dmsf_workflow_step_assignments.each do |assignment|
            if assignment.id == action.dmsf_workflow_step_assignment_id
              assignment.update_attribute(:user_id, user_id)
              return false
            end
          end
        end
    end
    return false
  end  
end

app/helpers/dmsf_workflows_helper.rb
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Picman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module DmsfWorkflowsHelper
  
  def render_principals_for_new_dmsf_workflow_users(workflow, dmsf_workflow_step_assignment_id, dmsf_file_revision_id)
    scope = workflow.delegates(params[:q], dmsf_workflow_step_assignment_id, dmsf_file_revision_id)
    principal_count = scope.count
    principal_pages = Redmine::Pagination::Paginator.new principal_count, 10, params['page']
    principals = scope.offset(principal_pages.offset).limit(principal_pages.per_page).all

    if dmsf_workflow_step_assignment_id
      s = content_tag('div', principals_radio_button_tags('step_action', principals), :id => 'users_for_delegate')
    else
      s = content_tag('div', principals_check_box_tags('user_ids[]', principals), :id => 'users')
    end

    links = pagination_links_full(principal_pages, principal_count, :per_page_links => false) {|text, parameters, options|
      link_to text, autocomplete_for_user_dmsf_workflow_path(workflow, parameters.merge(:q => params[:q], :format => 'js')), :remote => true      
    }

    s + content_tag('p', links, :class => 'pagination')
    s.html_safe           
  end
  
  def dmsf_workflow_steps_options_for_select(steps)
    options = Array.new
    options << [l(:dmsf_new_step), 0]
    steps.each do |step|
      options << [step.to_s, step]
    end
    options_for_select(options, 0)
  end   
  
  def dmsf_workflows_for_select(project, dmsf_workflow_id)
    options = Array.new    
    DmsfWorkflow.where(['project_id = ? OR project_id IS NULL', project.id]).each do |wf|
      options << [wf.name, wf.id]
    end
    options_for_select(options, :selected => dmsf_workflow_id)
  end  
  
  def principals_radio_button_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ radio_button_tag name, principal.id * 10, false, :id => nil } #{h principal}</label>\n"
    end
    s.html_safe    
  end
end

app/views/dmsf_workflows/_action.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<h3 class="title"><%= l(:field_label_dmsf_workflow) %></h3>

<%= form_tag({:controller => 'dmsf_workflows', :action => 'new_action'},              
              :method => :post,
              :id => 'new-action-form') do %>
  
  <%= hidden_field_tag :dmsf_workflow_step_assignment_id, params[:dmsf_workflow_step_assignment_id] %>
  <%= hidden_field_tag :dmsf_file_revision_id, params[:dmsf_file_revision_id] %>
  <p><label><%= radio_button_tag 'step_action', DmsfWorkflowStepAction::ACTION_APPROVE, true %> <%= l(:label_dmsf_wokflow_action_approve) %></label><br/></p>
  
  <p>
    <label><%= radio_button_tag 'step_action', DmsfWorkflowStepAction::ACTION_REJECT %> <%= l(:label_dmsf_wokflow_action_reject) %></label><br/>
    <%= text_area_tag :note, '', :placeholder => l(:message_dmsf_wokflow_note), :size => '38x2' %>
  </p>

  <p>
    <%= label_tag 'delegate', l(:label_dmsf_wokflow_action_delegate) %><br/>
    <%= text_field_tag 'user_search', nil %>    
    <%= javascript_tag "observeSearchfield('user_search', 'users_for_delegate', '#{ escape_javascript autocomplete_for_user_dmsf_workflow_path(@dmsf_workflow, :dmsf_workflow_step_assignment_id => params[:dmsf_workflow_step_assignment_id], :dmsf_file_revision_id => params[:dmsf_file_revision_id]) }')" %>    
    <%=  content_tag('div', principals_radio_button_tags('step_action', @dmsf_workflow.delegates(nil, params[:dmsf_workflow_step_assignment_id], params[:dmsf_file_revision_id])), :id => 'users_for_delegate') %>
  </p>
  
  <p class="buttons">
    <%= submit_tag l(:button_submit), :name => 'commit', :onclick => 'hideModal(this);' %>
    <%= submit_tag l(:button_cancel), :name => 'commit', :onclick => 'hideModal(this);' %>
  </p>
<% end %>

app/views/dmsf_workflows/_main.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<% @workflows = DmsfWorkflow.where(:project_id => @project.id) if @project && @workflows.nil?  %>  

<div class="contextual">
<% if @project %>
  <%= link_to l(:label_dmsf_workflow_new), new_dmsf_workflow_path(:project_id => @project.id), :class => 'icon icon-add' %>                
<% else %>
  <%= link_to l(:label_dmsf_workflow_new), new_dmsf_workflow_path, :class => 'icon icon-add' %>
<% end %>
</div>

<h2><%=l(:label_dmsf_workflow_plural)%></h2>

<table class="list">
  <thead><tr>
    <th><%=l(:field_name)%></th>    
    <th></th>
  </tr></thead>
  <tbody>
<% for workflow in @workflows %>
  <tr id="workflow-<%= workflow.id %>" class="<%= cycle('odd', 'even') %>">
    <td class="name"><%= link_to(h(workflow.name), dmsf_workflow_path(workflow)) %></td>    
    <td class="buttons">      
      <%= delete_link dmsf_workflow_path(workflow) %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

<% if @workflow_pages %>
  <p class="pagination"><%= pagination_links_full @workflow_pages %></p>
<% end %>

app/views/dmsf_workflows/_steps.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<% if @dmsf_workflow.project %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), settings_project_path(@project, :tab => 'dmsf_workflow') %> &#187; <%=h @dmsf_workflow %></h2>
<% else %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), dmsf_workflows_path %> &#187; <%=h @dmsf_workflow %></h2>
<% end %>

<%= labelled_form_for @dmsf_workflow do |f| %>
  <%= error_messages_for 'workflow' %>
  <div class="box tabular">
    <p><%= f.label :label_dmsf_workflow_name %><%= text_field_tag :name, @dmsf_workflow.name %><%= submit_tag l(:button_save) %></p>
  </div>  
<% end %>    

<div class="tab-content" id="tab-content-members">
 
<div class="splitcontentleft">  
<% steps = @dmsf_workflow.dmsf_workflow_steps.collect{|s| s.step}.uniq %>
<% if steps.any? %>
<table class="list">
  <thead><tr>
    <th><%= l(:label_dmsf_workflow_step) %></th>
    <th><%= l(:label_dmsf_workflow_approval_plural) %></th>
    <th><%=l(:button_sort)%></th>    
    <th/>
  </tr></thead>
  <tbody>      
  <% steps.each do |i|%>  
    <tr id="step-<%= i %>" class="<%= cycle 'odd', 'even' %> step">            
      <td class="step"><%= i %></td>
      <td class="approval">                
        <% @dmsf_workflow.dmsf_workflow_steps.collect{|s| (s.step == i) ? s : nil}.compact.each_with_index do |step, j| %>
          <% if j != 0 %>
            <b><%= step.soperator %></b>&nbsp
          <% end %>
          <%= link_to_user step.user %>
        <% end %>
      </td>        
      <td class="reorder">  
        <%= reorder_links('workflow_step', {:action => 'edit', :id => @dmsf_workflow, :step => i}, :put) %>
      </td>
      <td class="buttons">      
        <%= delete_link edit_dmsf_workflow_path(@dmsf_workflow, :step => i) %>
      </td>  
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
  <%= form_for(@dmsf_workflow, :url => edit_dmsf_workflow_path(@dmsf_workflow),
               :html => {:method => :post}) do |f| %>    
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag 'user_search', l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>    
    <%= javascript_tag "observeSearchfield('user_search', 'users', '#{ escape_javascript autocomplete_for_user_dmsf_workflow_path(@dmsf_workflow, :dmsf_workflow_step_assignment_id => nil, :dmsf_file_revision_id => nil, :project_id => @project ? @project.id : nil) }')" %>
    
    <div id="users">
      <%= render_principals_for_new_dmsf_workflow_users(@dmsf_workflow, nil, nil) %>
    </div>

    <p>
      <%= l(:label_dmsf_workflow_step) %>
      <%= select_tag 'step',
              dmsf_workflow_steps_options_for_select(steps),
              :id => 'selected_step', :style => "width:100px" %>              
    </p>
    <p><%= l(:label_dmsf_workflow_add_approver) %></p>
    <p><%= submit_tag l(:dmsf_and) %>&nbsp<%= l(:label_or) %>&nbsp<%= submit_tag l(:dmsf_or) %></p>
    </fieldset>
  <% end %>
</div>

</div>

app/views/dmsf_workflows/add_step.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<%= render 'steps' %>

app/views/dmsf_workflows/new.html.erb
<%# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2013   Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.%>

<% project = Project.find_by_id params[:project_id] if params[:project_id] %>
<% if project %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), settings_project_path(project, :tab => 'dmsf_workflow') %> &#187; <%=l(:label_dmsf_workflow_new)%></h2>
<% else %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), dmsf_workflows_path %> &#187; <%=l(:label_dmsf_workflow_new)%></h2>
<% end %>

<%= labelled_form_for @dmsf_workflow do |f| %>
  <%= error_messages_for 'dmsf_workflow' %>
  <div class="box tabular">
    <p><%= f.label :label_dmsf_workflow_name %><%= text_field_tag :name %></p>
    <% if project %>
      <p><%= hidden_field_tag :project_id, project.id %></p>
    <% end %>
  </div>
  <%= submit_tag l(:button_create) %>
<% end %>